openapi: 3.0.0

info:
  description: |
    This is the RESTful API for a user to manage backup codes in Asgardeo.
  version: "v1"
  title: "Asgardeo - Backup Code API Definition"
servers:
- url: https://api.asgardeo.io/t/{organization-name}/api/users/v1

security:
  - OAuth2: []

tags:
  - name: me
    description: Operations for the authenticated user.

paths:
  /me/backup-codes:
    post:
      description:
        "This API is used to generate backup codes.\n\n<b>Scope required:</b>``internal_login``"
      summary: |
        Generate backup codes
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackupCodeResponse'
        401:
          description: Unauthorized
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v1/me/backup-codes' \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer {bearer_token}'  \
            -d ''          
      tags:
        - me
    get:
      tags:
        - me
      summary: Retrieve remaining backup codes count
      description:
        "This API is used to retrieve the count of remaining backup codes of the authenticated user.\n\n<b>Scope required:</b>``internal_login``"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemainingBackupCodeResponse'
        401:
          description: Unauthorized
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'GET' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v1/me/backup-codes' \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer {bearer_token}'                
    delete:
      tags:
        - me
      summary: Delete backup codes
      description:
        "This API is used to delete backup codes of the authenticated user.\n\n<b>Scope required:</b>``internal_login``"
      responses:
        204:
          description: Backup codes deleted successfully.
        401:
          description: Unauthorized
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'DELETE' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v1/me/backup-codes' \
            -H 'accept: */*' \
            -H 'Authorization: Bearer {bearer_token}'                
components:
  schemas:
    Error:
      type: object
      description: Backup code error.
      required:
        - code
        - message
        - traceId
      properties:
        code:
          type: string
          example: "some_error_code"
          description: Error code.
        message:
          type: string
          example: "Some Error Message"
          description: Error message.
        description:
          type: string
          example: "Some Error Description"
          description: Error description.
        traceId:
          type: string
          example: "Some Correlation for Error Instance"
          description: Error trace id.
    #-----------------------------------------------------
    # Backup code Response object
    #-----------------------------------------------------
    BackupCodeResponse:
      type: object
      description: Backup code response.
      properties:
        backupCodes:
          type: array
          description: Backup codes of the authenticated user.
          items:
            type: string
            example: 123456

    RemainingBackupCodeResponse:
      type: object
      description: Remaining backup code response.
      properties:
        remainingBackupCodesCount:
          description: Remaining backup codes of the authenticated user.
          type: integer
          example: 4

  securitySchemes:
    OAuth2:
      type: oauth2
      description: "You can use the following OAuth grant type to securely access the respective API endpoints.
      \n\n **Authorization Code OAuth Flow**
      \n\n Authorization URL: 'https://api.asgardeo.io/t/{org-name}/oauth2/authorize'
      \n\n This flow type is used for the ```me``` endpoint of backup-codes APIs. You can use the following scope for this endpoints.
        \n\n - ```internal_login```: Grant permission for an authenticated user for self management."